### PR TITLE
fix error directory

### PR DESCRIPTION
**Pull request by ghost**
hello, without getcwd i have error for find the file.

### CODE REVIEW

**Comment by giovanigenerali** [comment]
@eldinomick what php version are you running?

**Comment by cadot-info** [comment]
7.3

17 sept. 2020 13:41:48 Giovani Generali <notifications@github.com>:

**Comment by giovanigenerali** [comment]
@eldinomick thanks, I fixed it in the latest release and I'll close this PR.

**Comment by cadot-info** [comment]
thanks for your job.
Actually your last commit don't resolve my issue.
I have the problem, it's my call at your code.
I repair in many times... maybe ;-)
Thanks

**Pull request closed without merging**
